---
- name: Set up apache on servers, set timezones
  hosts: all
  become: yes
  remote_user: ubuntu

  tasks:
    - name: Install Apache
      apt: 
        - name=apache2 
        - update_cache=yes 
      state = present

    - name: Get instance IP address
      shell: hostname -I
      register: ip_address

    - name: timezone  Africa/Lagos
      timezone: name = Africa/Lagos

    - name: pull instance timezone
      shell: echo $(timedatectl | grep "Time zone")
      register: timezone

    - name:  HTML page display instance timezone and IP address
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head>
              <title>EC2 Instance</title>
            </head>
            <body>
              <h1>Instance Information</h1>
              <p>{{ timezone.stdout }}</p>
              <p>IP Address: {{ ip_address.stdout }}</p>
              <p>omo!!!!!!!!!!!!!!!!!!!!</p>
            </body>
          </html>