- name: Install Apache
  hosts: example
  become: yes
  tasks:
    - name: update distro
      apt:
      update_cache: yes
      upgrade: dist

    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Start Apache
      service:
        name: apache2
        state: started